In [31]:
import pandas as pd
import numpy as np

In [32]:
from selenium import webdriver
from selenium.webdriver.common.by import By

In [33]:
import math
import time
import pickle

### Creating Custom Function

In [34]:
def create_df(data):
    columns = data.split('\n')[0].split(" ")
    cols = columns[:-2] + [' '.join(columns[-1:-3:-1][::-1])]
    data_list = data.split("\n")[1:]
    arr = np.array(data_list)
    df = pd.DataFrame(arr.reshape((int(arr.shape[0] / 8)), 8))
    
    df[cols[2:10]] = df[2].str.split(expand = True)
    df.drop(columns = 2,inplace=True)
    
    recent_form = ['-'.join(item) for item in np.array(df.iloc[:, 2:7])]
    df['recent_form'] = recent_form
    df.drop(columns = [i for i in range(3,8)],inplace = True)
    
    df.columns = cols
    
    for i in cols[2:6]:
        df[i] = df[i].astype(int)
    df['NRR'] = df['NRR'].apply(lambda x : float(x))
    df['PTS'] = df['PTS'].apply(lambda x : int(x))
    
    return df

In [42]:
def ipl_table(year):
    
    url = f"https://www.iplt20.com/points-table/men/{year}"
    
    driver = webdriver.Chrome()
    driver.get(url)

    time.sleep(10)

    table_xpath = '/html/body/div[1]/section/div/div/div[1]/div/div/div[1]/div/div/div[2]/div/div/div/table'
    data = driver.find_element(By.XPATH, table_xpath).text

    driver.quit()

    return create_df(data)

In [43]:
ipl_table(2024)

  POS  TEAM   P  W   L  NR    NRR         FOR     AGAINST  PTS RECENT FORM
0   1   KKR  14  9   3   2  1.428  2389/225.0  2135/232.2   20   N-N-W-W-W
1   2   SRH  14  8   5   1  0.414  2605/247.0  2599/256.3   17   W-N-W-L-W
2   3    RR  14  8   5   1  0.273  2334/252.1  2310/257.1   17   N-L-L-L-L
3   4   RCB  14  7   7   0  0.459  2758/269.0  2646/270.1   14   W-W-W-W-W
4   5   CSK  14  7   7   0  0.392  2524/274.4  2415/274.3   14   L-W-L-W-L
5   6    DC  14  7   7   0 -0.377  2573/267.0  2762/275.5   14   W-L-W-L-W
6   7   LSG  14  7   7   0 -0.667  2483/277.5  2521/262.3   14   W-L-L-L-W
7   8    GT  14  5   7   2 -1.063  2040/238.2  2101/218.2   12   N-N-W-L-L
8   9  PBKS  14  5   9   0 -0.353  2487/274.3  2612/277.3   10   L-W-L-L-W
9  10    MI  14  4  10   0 -0.318  2568/268.5  2660/269.3    8   L-L-W-L-L

In [44]:
ipl_table(2018)

  POS  TEAM   P  W  L  NR    NRR         FOR     AGAINST  PTS RECENT FORM
0   1   SRH  14  9  5   0  0.284  2230/273.3  2193/278.4   18   L-L-L-W-W
1   2   CSK  14  9  5   0  0.253  2488/275.3  2433/277.1   18   W-L-W-L-W
2   3   KKR  14  8  6   0 -0.070  2363/265.1    2425/270   16   W-W-W-L-L
3   4    RR  14  7  7   0 -0.250  2130/255.3  2141/249.2   14   W-L-W-W-W
4   5    MI  14  6  8   0  0.317  2380/278.4  2282/277.3   12   L-W-L-W-W
5   6   RCB  14  6  8   0  0.129  2322/264.4  2383/275.4   12   L-W-W-W-L
6   7  PBKS  14  6  8   0 -0.502  2210/268.4  2259/258.5   12   L-L-L-L-L
7   8    DD  14  5  9   0 -0.222    2297/258  2304/252.3   10   W-W-L-L-L